### ISSUE TITLE
Jetpack plugin issues

### ISSUE THREAD

**Issue by frol** [ViBiOh/docker-wordpress#1]
*First, I want to say thank you to @ViBiOh for this nice packaging of all pieces necessary to run Wordpress! Great job, man!*

*I will just leave this information here, but it might be useful to somehow address this topic in the README.*

There are a couple of quirks required to have Jetpack running, so you can use [Calypso](https://developer.wordpress.com/calypso/):

* You will need `php-xmlrpc` and `php-ctype` modules installed (here is my PR https://github.com/ViBiOh/docker-php/pull/1)
* If you use another proxy/balancer (e.g. another Nginx) in front of the provided and configured with docker-compose, you will need to set `X-Forwarded-Port` header, otherwise Jetpack will fail with the error messages like "Can't access this site data", "There was an error retrieving your site settings. Make sure your Jetpack is up to date", "requested method jetpack.testConnection does not exist.", "requested method jetpack.jsonAPI does not exist." (I found this URL very useful to debug the XMLRPC issues - https://public-api.wordpress.com/rest/v1/sites/vulcanpost.com/posts (replace the domain name with yours))
* You can also receive HTTP 502 Error while trying to connect Jetpack to Wordpress.com and the following error might be found in the logs "upstream sent too big header while reading response header from upstream", this happens due to a huge header response with a number of `Set-Cookie` headers. Increase buffers size, e.g. `proxy_buffer*` configs in Nginx.

Here is my Nginx config (keep in mind that you cannot just close wp-admin endpoint with HTTP Basic Authentication, for example, because Calypso will fail to upload images):

```
server {

    listen 0.0.0.0;
    server_name interrogative.prostoksi.com;

    location / {
        proxy_pass http://127.0.0.1:7000;
        proxy_buffering off;
        proxy_buffer_size 256k;
        proxy_buffers 8 128k;
        proxy_busy_buffers_size 256k;
        include proxy_params;
        proxy_set_header X-Forwarded-Port $server_port;
    }
}
```

~~NOTE: I've managed to make my hosted wordpress working with Calypso, but one issue is still here. I cannot upload any images via Calypso interface (though I can via my hosted admin interface), the error message is "The file could not be uploaded because an error occurred while uploading."~~ `php-json` is required also!

**Comment by ViBiOh** [comment]
Hello @frol, thanks for you interest in my work.

I saw recently the lack of php dependencies with Jetpacks on a professionnel context and that was the solution I found too.

Concerning another reverse-proxy, I recently switch to [traefik](https://traefik.github.io) and I've not seen issue with Jetpacks, I will look for that.

Thank you,

**Comment by frol** [comment]
@ViBiOh I've just figured out the issue with Calypso image uploading - `php-json` is required, so I adde it to my PR.

**Comment by ViBiOh** [comment]
@frol I agree to add php-json (it was needed for docker/phpmyadmin for example, I can change it now). For the reverse-proxy I'm not so convinced because it actually works with another reverse-proxy. Have you any doc or tests ? I'll look for that as soon as I can (on Friday maybe... little busy at the moment).

The build is started for `php-json` here https://hub.docker.com/r/vibioh/php/builds/bixllukqrs4pahvftb8a9kk/

**Comment by frol** [comment]
@ViBiOh I have been debuging Jetpack plugin and found that it uses $_SERVER['SERVER_PORT'] (wp-content/plugins/jetpack/class.jetpack-signature.php) when verifying signature, but `fastcgi.conf` in your bundled nginx has `fastcgi_params SERVER_PORT $server_port;` and I couldn't convince Nginx to pass proper port other than using `X-Forwarded-Port` header.

**Comment by ViBiOh** [comment]
@frol ok, it's merged. I have also added openssl plugin for php :)

**Comment by frol** [comment]
@ViBiOh Great! Thanks!
