### ISSUE TITLE
Docker Compose or other orchestration

### ISSUE THREAD

**Issue by frol** [ViBiOh/docker-wordpress#2]
Why have you removed the `docker-compose.yml`? It worked just fine as a template starting point. I saw in commits that you have replaced it with a bash script (I would say it was a step back), but later you have completely removed all orchestration. Why?

**Comment by ViBiOh** [comment]
Hi Frol,

I moved it to https://github.com/ViBiOh/rancher-catalog/blob/master/templates/wordpress/0/docker-compose.yml as I frequently use Rancher for containers management (allow use of variable in docker-compose).

I need to update README to indicate it.

**Comment by frol** [comment]
@ViBiOh Yeah, it would be greate to have the reference in the README.

**Comment by ViBiOh** [comment]
@frol Sorry for not updating README at the same time, it's fixed with improvement with the use of Docker Compose interpolations

**Comment by frol** [comment]
@ViBiOh Thank you! Though, I was fine. I discovered this thing only because I wanted to give a link to this project as an example.
